config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout',
                                                 password: 'secret', confirmation: 'verification', unlock: 'unblock',
                                                 registration: 'register', sign_up: 'cmon_let_me_in' }

  # devise_scope :user do
  #   get 'login', to: 'devise/sessions#new'
  #   get 'logout', to: 'devise/sessions#destroy'
  #   get 'password', to: 'devise/passwords#new'
  #   get 'register', to: 'devise/registrations#new'
  # end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'home#index'

  namespace :admins do
    resources :pages do
      collection do
        get :published
        get :unpublished
      end
    end
    resources :blogs do
      collection do
        get :published
        get :unpublished
      end
    end
    resources :rooms
    resources :categories
    resources :bookings
  end

  resources :pages, only: [:index, :show]
  resources :blogs, only: [:index, :show]
  resources :rooms, only: [:index, :show]
  resources :categories, only: [:index, :show]
  resources :bookings, except: [:edit, :update, :destroy]
  resources :search_results, only: [:index]
end

app/views/admins/pages/_form.html.erb
<%= simple_form_for @page, url: [:admins, @page] do |form| %>
  <%= form.input :title, label: "Tytuł", input_html: { class: "form-control mb-3" } %>
  <%= form.input :seo_title, label: "Tytuł SEO", input_html: { class: "form-control mb-3" } %>
  <%= form.input :content, label: "Treść", input_html: { class: "form-control mb-3" } %>
  <%= form.input :state, collection: ['published', 'unpublished'], include_blank: false, label: "Published", input_html: { class: "form-control mb-3" } %>
  <%= form.input :photo, as: :file, label: "Zdjęcie", input_html: { class: "form-control mb-3" } %>
  <div class="form-image">
    <img src="<%= @page.photo %>" class="form-img" alt="">
  </div>
  <%= form.button :submit, value: "Zapisz", class: "btn btn-primary create-btn mt-3" %>
<% end %>

app/views/admins/pages/edit.html.erb
<div class="heading-bg">
  <h1 class="heading-title">Edytuj</h1>
  <%= link_to 'Wstecz', admins_pages_path, class: "btn btn-light" %>
</div>

<div class="admin-content-edit">
  <%= render 'form' %>
</div>

app/views/admins/pages/index.html.erb
<div class="heading-bg">
  <h1 class="heading-title">Strony</h1>
  <div class="heading-button-box">
    <%= link_to 'Opublikowane', admins_pages_path(state: 'published'), class: "btn btn-light" %>
    <%= link_to 'Nieopublikowane', admins_pages_path(state: 'unpublished'), class: "btn btn-light" %>
  </div>
  <%= link_to 'Stwórz nową stronę', new_admins_page_path, class: "btn btn-primary" %>
</div>

<div class="container pages-index-container">
  <div class="flickr_pagination mt-4 mb-4">
    <%= will_paginate @pages, :container => false %>
  </div>
  <% @pages.each do |page| %>
    <div class="card pages-index-card">
      <img src="<%= page.photo %>" class="card-img-top pages-index-img" alt="<%= page.seo_title %>">
      <div class="card-body">
        <h5 class="card-title pages-index-title"><%= page.title %></h5>
        <p class="card-text pages-index-text"><%= page.content %></p>
        <%= link_to 'Zobacz', page_path(page), class: "btn btn-success" %>
        <%= link_to 'Edytuj', edit_admins_page_path(page), class: "btn btn-primary" %>
        <%= link_to 'Usuń', admins_page_path(page), class: "btn btn-danger", method: :delete %>
      </div>
    </div>
  <% end %>
  <div class="flickr_pagination mt-4 mb-4">
    <%= will_paginate @pages, :container => false %>
  </div>
</div>

app/views/admins/pages/new.html.erb
<div class="heading-bg">
  <h1 class="heading-title">Dodaj nową stronę</h1>
  <%= link_to 'Wstecz', admins_pages_path, class: "btn btn-light" %>
</div>

<div class="admin-content-new">
  <%= render 'form' %>
</div>

app/views/admins/pages/published.html.erb
<div class="heading-bg">
  <h1 class="heading-title">Strony</h1>
  <%= link_to 'Wróć do stron', admins_pages_path, class: "btn btn-light" %>
  <%= link_to 'Stwórz nową stronę', new_admins_page_path, class: "btn btn-primary" %>
</div>

<div class="container pages-index-container">
  <h1 class="mb-5">Opublikowane</h1>
  <% @pages.each do |page| %>
    <div class="card pages-index-card">
      <img src="<%= page.photo %>" class="card-img-top pages-index-img" alt="<%= page.seo_title %>">
      <div class="card-body">
        <h5 class="card-title pages-index-title"><%= page.title %></h5>
        <p class="card-text pages-index-text"><%= page.content %></p>
        <%= link_to 'Zobacz', page_path(page), class: "btn btn-success" %>
        <%= link_to 'Edytuj', edit_admins_page_path(page), class: "btn btn-primary" %>
        <%= link_to 'Usuń', admins_page_path(page), class: "btn btn-danger", method: :delete %>
      </div>
    </div>
  <% end %>
</div>

app/views/admins/pages/unpublished.html.erb
<div class="heading-bg">
  <h1 class="heading-title">Strony</h1>
  <%= link_to 'Wróć do stron', admins_pages_path, class: "btn btn-light" %>
  <%= link_to 'Stwórz nową stronę', new_admins_page_path, class: "btn btn-primary" %>
</div>

<div class="container pages-index-container">
  <h1 class="mb-5">Nieopublikowane</h1>
  <% @pages.each do |page| %>
    <div class="card pages-index-card">
      <img src="<%= page.photo %>" class="card-img-top pages-index-img" alt="<%= page.seo_title %>">
      <div class="card-body">
        <h5 class="card-title pages-index-title"><%= page.title %></h5>
        <p class="card-text pages-index-text"><%= page.content %></p>
        <%= link_to 'Zobacz', page_path(page), class: "btn btn-success" %>
        <%= link_to 'Edytuj', edit_admins_page_path(page), class: "btn btn-primary" %>
        <%= link_to 'Usuń', admins_page_path(page), class: "btn btn-danger", method: :delete %>
      </div>
    </div>
  <% end %>
</div>