config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout',
                                                 password: 'secret', confirmation: 'verification', unlock: 'unblock',
                                                 registration: 'register', sign_up: 'cmon_let_me_in' }

  # devise_scope :user do
  #   get 'login', to: 'devise/sessions#new'
  #   get 'logout', to: 'devise/sessions#destroy'
  #   get 'password', to: 'devise/passwords#new'
  #   get 'register', to: 'devise/registrations#new'
  # end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'home#index'

  namespace :admins do
    resources :pages do
      collection do
        get :published
        get :unpublished
      end
    end
    resources :blogs do
      collection do
        get :published
        get :unpublished
      end
    end
    resources :rooms
    resources :categories
    resources :bookings
  end

  resources :pages, only: [:index, :show]
  resources :blogs, only: [:index, :show]
  resources :rooms, only: [:index, :show]
  resources :categories, only: [:index, :show]
  resources :bookings, except: [:edit, :update, :destroy]
  resources :search_results, only: [:index]
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :blogs
  
  validates :name, presence: true, length: { minimum: 3, maximum: 50 }
end

app/controllers/admins/categories_controller.rb
# frozen_string_literal: true

module Admins
  class CategoriesController < ApplicationController
    before_action :find_category, only: [:edit, :update, :destroy]
    layout 'admin'

    access admin: :all

    def index
      @categories = Category.all
    end

    def new
      @category = Category.new
    end

    def create
      @category = Category.new(category_params)

      if @category.save
        redirect_to admins_categories_path, notice: 'Kategoria została utworzona prawidłowo'
      else
        render :new, alert: 'Wystąłpił błąd podczas dodawania kategorii'
      end
    end

    def edit; end

    def update
      if @category.update(category_params)
        redirect_to admins_categories_path, notice: 'Kategoria została zaktualizowana prawidłowo'
      else
        render :edit, alert: 'Wystąpił błąd podczas aktualizowania kategorii'
      end
    end

    def destroy
      @category.destroy

      redirect_to admins_categories_path, alert: 'Kategoria została usunięta'
    end

    def category_params
      params.require(:category).permit(:name)
    end

    def find_category
      @category = Category.find(params[:id])
    end
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :find_category, only: [:show]

  def index
    @categories = Category.all
  end

  def show
    @blogs = Blog.where(category_id: params[:id])
  end

  private

  def find_category
    @category = Category.find(params[:id])
  end
end

app/views/admins/categories/_form.html.erb
<%= simple_form_for @category, url: [:admins, @category] do |form| %>
  <%= form.input :name, label: "Kategoria", input_html: { class: "form-control mb-3" } %>
  <%= form.button :submit, value: "Zapisz", class: "btn btn-primary create-btn mt3" %>
<% end %>

app/views/admins/categories/edit.html.erb
<div class="heading-bg">
  <h1 class="heading-title">Edytuj</h1>
  <%= link_to 'Wstecz', admins_categories_path, class: "btn btn-light" %>
</div>

<div class="admin-content-edit">
  <%= render 'form' %>
</div>

app/views/admins/categories/index.html.erb
<div class="heading-bg">
  <h1 class="heading-title">Kategorie</h1>
  <%= link_to 'Nowa kategoria', new_admins_category_path, class: "btn btn-primary" %>
</div>
<div class="container pages-index-container">
  <table class="table admin-categories-table mt-5">
    <thead class="thead-dark">
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Nazwa</th>
      <th scope="col">Opcje</th>
    </tr>
    </thead>
    <tbody>
    <% @categories.each do |category| %>
      <tr>
        <th scope="row"><%= category.id %></th>
        <td><%= category.name %></td>
        <td>
          <%= link_to 'Zobacz', category_path(category), class: "btn btn-success" %>
          <%= link_to 'Edytuj', edit_admins_category_path(category), class: "btn btn-primary" %>
          <%= link_to 'Usuń', admins_category_path(category), class: "btn btn-danger", method: :delete %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/admins/categories/new.html.erb
<div class="heading-bg">
  <h1 class="heading-title">Dodaj nową kategorię</h1>
  <%= link_to 'Wstecz', admins_categories_path, class: "btn btn-light" %>
</div>

<div class="admin-content-new">
  <%= render 'form' %>
</div>