config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout',
                                                 password: 'secret', confirmation: 'verification', unlock: 'unblock',
                                                 registration: 'register', sign_up: 'cmon_let_me_in' }

  # devise_scope :user do
  #   get 'login', to: 'devise/sessions#new'
  #   get 'logout', to: 'devise/sessions#destroy'
  #   get 'password', to: 'devise/passwords#new'
  #   get 'register', to: 'devise/registrations#new'
  # end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'home#index'

  namespace :admins do
    resources :pages do
      collection do
        get :published
        get :unpublished
      end
    end
    resources :blogs do
      collection do
        get :published
        get :unpublished
      end
    end
    resources :rooms
    resources :categories
    resources :bookings
  end

  resources :pages, only: [:index, :show]
  resources :blogs, only: [:index, :show]
  resources :rooms, only: [:index, :show]
  resources :categories, only: [:index, :show]
  resources :bookings, except: [:edit, :update, :destroy]
  resources :search_results, only: [:index]
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @rooms = Room.all.order('created_at DESC').limit(3)
    @blogs = Blog.all.published.order('created_at DESC').limit(3)
    @pages = Page.all.published.order('created_at DESC').limit(3)
  end
end

app/views/home/_about_section.html.erb
<section class="about">
  <div class="container about-container">
    <div class="about-image">
      <%= image_tag('about-image.jpg', :alt => 'Obraz przedstawiający krzesła przy plaży', class: 'about-img') %>
    </div>
    <div class="about-content">
      <h1 class="about-title">SunriseHotel - Przestronny i Nowoczesny Hotel</h1>
      <span class="about-stars"><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i></span>
      <p class="about-text">
        Zatrzymaj się w ukochanym miejscu w Hiszpanii! Nasz nowoczesny i luksusowy hotel, położony
        zaraz przy prywatnej piaszczystek plaży w południowej części Hiszpanii, zapewni Ci niezapomniane wakacje.
        Z balkonu i tarasu roztaczają się niesamowite widoki na Morze Śródziemnomorskie.
      </p>
      <div class="about-icons-container">
        <div class="icon-box">
          <i class="fas fa-bed about-icon"></i>
          <p class="icon-box-text">48 Pokoi</p>
        </div>
        <div class="icon-box">
          <i class="fas fa-utensils about-icon"></i>
          <p class="icon-box-text"> 3 Restauracje</p>
        </div>
        <div class="icon-box">
          <i class="fas fa-cocktail about-icon"></i>
          <p class="icon-box-text"> 4 Bary</p>
        </div>
        <div class="icon-box">
          <i class="fas fa-umbrella-beach about-icon"></i>
          <p class="icon-box-text">Prywatna plaża</p>
        </div>
        <div class="icon-box">
          <i class="fas fa-swimmer about-icon"></i>
          <p class="icon-box-text">Prywatna plaża</p>
        </div>
        <div class="icon-box">
          <i class="fas fa-wifi about-icon"></i>
          <p class="icon-box-text">Darmowe Wi-Fi</p>
        </div>
      </div>
      <%= link_to 'Rezerwacje', root_path, class: "btn btn-primary about-btn" %>
    </div>
  </div>
</section>

app/views/home/_attractions_section.html.erb
<section class="attractions">
  <div class="wrapper">
    <h2>Atrakcje</h2>
  </div>

  <div class="container attractions-container">
    <div class="row row-cols-1 row-cols-lg-3">
      <% @pages.each do |page| %>
        <div class="col mb-4">
          <div class="card h-100 text-center attraction-card">
            <img src="<%= page.photo %>" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title"><%= page.title %></h5>
              <p class="card-text"><%= page.content %></p>
            </div>
            <div class="card-footer">
              <%= link_to 'Czytaj dalej', page_path(page), class: "btn btn-success attraction-card-btn" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="btn-container">
    <%= link_to 'Wszystkie atrakcje', pages_path, class: "btn btn-success attraction-card-btn" %>
  </div>

</section>

app/views/home/_blogs_section.html.erb
<section class="blogs">
  <div class="wrapper">
    <h2>Blog</h2>
  </div>

  <div class="container blogs-container">
    <div class="row row-cols-1 row-cols-lg-3">
      <% @blogs.each do |blog| %>
        <div class="col mb-4">
          <div class="card h-100 text-center blog-card">
            <img src="<%= blog.photo %>" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title"><%= blog.title %></h5>
              <p class="card-text"><%= blog.content %></p>
            </div>
            <div class="card-footer">
              <%= link_to 'Czytaj dalej', blog_path(blog), class: "btn btn-success blog-card-btn" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="btn-container">
    <%= link_to 'Wszystkie artykuły', blogs_path, class: "btn btn-success blog-card-btn" %>
  </div>
</section>

app/views/home/_gallery_section.html.erb
<section class="gallery-section">
      <div class="photo-container">
          <div class="gallery-photo-1">
            <div class="gallery-shadow"></div>
          </div>
          <div class="gallery-photo-2">
            <div class="gallery-shadow"></div>
          </div>
          <div class="gallery-photo-3">
            <div class="gallery-shadow"></div>
          </div>
          <div class="gallery-photo-4">
            <div class="gallery-shadow"></div>
          </div>
      </div>
      <div class="photo-container">
          <div class="gallery-photo-5">
            <div class="gallery-shadow"></div>
          </div>
          <div class="gallery-photo-6">
            <div class="gallery-shadow"></div>
          </div>
          <div class="gallery-photo-7">
            <div class="gallery-shadow"></div>
          </div>
          <div class="gallery-photo-8">
            <div class="gallery-shadow"></div>
          </div>
      </div>
</section>

app/views/home/_header.html.erb
<header class="header">
  <div class="header-img">
    <div class="hero-shadow"></div>
  </div>
  <div class="header-content">
    <div class="header-content-box">
      <h2 class="header-title">Zarezerwój Swój Pobyt</h2>
      <p class="header-text"> Witaj w Hotelu Sunrise - najlepszym z hoteli południowej Hiszpanii</p>
    </div>
    <%= render 'search_form' %>
  </div>
</header>

app/views/home/_info_section.html.erb
<section class="info-section">
  <div class="container info-container">
    <div class="row">
      <div class="col-sm-6 col-lg-3 info-box">
        <i class="fas fa-spa info-icon"></i>
        <p class="info-title">9</p>
        <p class="info-text">Lat Doświadczenia</p>
      </div>
      <div class="col-sm-6 col-lg-3 info-box">
        <i class="fas fa-utensils info-icon"></i>
        <p class="info-title">4</p>
        <p class="info-text">Renomowane Restauracje</p>
      </div>
      <div class="col-sm-6 col-lg-3 info-box">
        <i class="fas fa-bed info-icon"></i>
        <p class="info-title">48</p>
        <p class="info-text">Komfortowych Pokoi</p>
      </div>
      <div class="col-sm-6 col-lg-3 info-box">
        <i class="far fa-smile info-icon"></i>
        <p class="info-title">64783</p>
        <p class="info-text">Zadowolonych Klientów</p>
      </div>
    </div>
  </div>
</section>

app/views/home/_map_section.html.erb
<section class="map">
  <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3060.889321965246!2d4.075427650840378!3d39.89911020843898!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x12958ab283b08a5b%3A0xdb4f26347947f0f5!2sPlatja%20de%20Son%20Bou!5e0!3m2!1spl!2spl!4v1623057242861!5m2!1spl!2spl" class="map" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
</section>

app/views/home/_rooms_section.html.erb
<section class="rooms">
  <div class="wrapper">
    <h2>Nasze Pokoje</h2>
  </div>

  <div class="container rooms-container">
    <div class="row row-cols-1 row-cols-lg-3">
      <% @rooms.each do |room| %>
        <div class="col mb-4">
          <div class="card h-100 text-center room-card">
            <img src="<%= room.photo %>" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title">Apartament <%= room.name %></h5>
              <p class="card-text"><%= room.description %></p>
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item"><i class="fas fa-male"></i> 2</li>
              <li class="list-group-item"><i class="fas fa-mug-hot"></i> Śniadanie, obiad, kolacja</li>
              <li class="list-group-item"><i class="fas fa-expand-arrows-alt"></i> Wielkość: <%= room.size %></li>
              <li class="list-group-item">Ceny od: <%= room.base_price %></li>
            </ul>
            <div class="card-body">
              <%= link_to 'Zobacz', room_path(room), class: "btn btn-success room-card-btn" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="btn-container">
    <%= link_to 'Wszystkie pokoje', rooms_path, class: "btn btn-success room-card-btn" %>
  </div>
</section>

app/views/home/_search_form.html.erb
<%= simple_form_for :search_form, url: search_results_path, method: :get do |form| %>
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="form-group header-form-group">
          <div class="header-form-one">
            <small class="form-text">Data przyjazdu:</small>
            <%= form.date_field :start_date, class: 'form-control datetimepicker-input', 'data-target': "#datetimepicker4" %>
          </div>
          <div class="header-form-two">
            <small class="form-text">Data wyjazdu:</small>
            <%= form.date_field :end_date, class: 'form-control datetimepicker-input', 'data-target': "#datetimepicker4" %>
          </div>
          <div class="header-form-btn">
            <%= form.button :submit, value: "Szukaj", class: "btn btn-primary header-btn" %>
          </div>
        </div>

      </div>
    </div>
  </div>
<% end %>

app/views/home/_start_section.html.erb
<section class="start">
  <div class="start-img">
    <div class="hero-shadow"></div>
  </div>
  <div class="start-content">
    <h2 class="start-title">Jesteś gotowy, aby zarezerwować pokój?</h2>
    <p class="start-text">Z nami dokonasz bezpiecznej rezerwacji online. Sięgnij po marzenia, albo zadaj nam pytanie kontaktujac się z nami.</p>
    <div class="start-btn-box">
      <%= link_to 'Rezerwacja', root_path, class: 'btn btn-success start-btn-one' %>
      <a href="#" class="btn btn-success start-btn-two">Skontaktuj się</a>
    </div>
  </div>

</section>

app/views/home/_testimonials_section.html.erb
<section class="testimonials">
  <div class="wrapper">
    <h2>Opinie</h2>
  </div>
  <div class="container testimonials-container">
    <div id="carouselExampleControls" class="carousel slide justify-content-center" data-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <div class="media testimonials-media">
            <%= image_tag('kobieta1.jpg', :alt => 'Kobieta', class: 'testimonials-img') %>
            <div class="media-body">
              <span class="testimonials-stars"><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i></span>
              <p class="testimonials-text">Sunrise Hotel to piękny przytulny hotel w pobliżu piaszczystych plaż. Osobisty przewodnik był pomocny i szybko odpowiedział na wszystkie pytania. Bardzo miła obsługa i kuchnia. Świetnie się bawiliśmy.</p>
              <h5 class="mt-0 testimonials-name">Joanna Nowak</h5>
            </div>
          </div>
        </div>
        <div class="carousel-item">
          <div class="media testimonials-media">
            <%= image_tag('kobieta2.jpg', :alt => 'Kobieta', class: 'testimonials-img') %>
            <div class="media-body">
              <span class="testimonials-stars"><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i></span>
              <p class="testimonials-text">Możesz rozpocząć dzień od zimnego drinka dostarczonego przez barmana o dowolnej porze, a następnie cieszyć się wakacjami. Po powrocie z plaży smaczny obiad i domowe ciasto.</p>
              <h5 class="mt-0 testimonials-name">Alicja Janosz</h5>
            </div>
          </div>
        </div>
        <div class="carousel-item">
          <div class="media testimonials-media">
            <%= image_tag('mężczyzna1.jpg', :alt => 'Mężczyzna', class: 'testimonials-img') %>
            <div class="media-body">
              <span class="testimonials-stars"><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i></span>
              <p class="testimonials-text">Przyjechaliśmy po raz pierwszy do Sunrise Hotel i świetnie się bawiliśmy w tym niesamowitym hotelu! W środku mieliśmy wszystko. Hotel był bardzo czysty i bardzo wygodny. Dziękujemy za bardzo przyjemny pobyt!</p>
              <h5 class="mt-0 testimonials-name">Jan Kowalski</h5>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/index.html.erb
<%= render 'header' %>
<%= render 'about_section' %>
<%= render 'rooms_section' %>
<%= render 'gallery_section' %>
<%= render 'blogs_section' %>
<%= render 'info_section' %>
<%= render 'attractions_section' %>
<%= render 'testimonials_section' %>
<%= render 'start_section' %>
<%= render 'map_section' %>