config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout',
                                                 password: 'secret', confirmation: 'verification', unlock: 'unblock',
                                                 registration: 'register', sign_up: 'cmon_let_me_in' }

  # devise_scope :user do
  #   get 'login', to: 'devise/sessions#new'
  #   get 'logout', to: 'devise/sessions#destroy'
  #   get 'password', to: 'devise/passwords#new'
  #   get 'register', to: 'devise/registrations#new'
  # end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'home#index'

  namespace :admins do
    resources :pages do
      collection do
        get :published
        get :unpublished
      end
    end
    resources :blogs do
      collection do
        get :published
        get :unpublished
      end
    end
    resources :rooms
    resources :categories
    resources :bookings
  end

  resources :pages, only: [:index, :show]
  resources :blogs, only: [:index, :show]
  resources :rooms, only: [:index, :show]
  resources :categories, only: [:index, :show]
  resources :bookings, except: [:edit, :update, :destroy]
  resources :search_results, only: [:index]
end

app/views/layouts/_admin_nav.html.erb
<div class="admin-nav-box">
  <nav class="admin-nav">
    <div class="nav-brand">
      <%= link_to 'SunriseHotel', admins_pages_path, class: "nav-brand-text" %>
      <p class="admin-panel-txt">Admin Panel</p>
    </div>
    <div class="nav-items">
      <%= link_to 'Strony', admins_pages_path, class: "admin-nav-item" %>
      <%= link_to 'Artykuły', admins_blogs_path, class: "admin-nav-item" %>
      <%= link_to 'Kategorie', admins_categories_path, class: "admin-nav-item" %>
      <%= link_to 'Pokoje', admins_rooms_path, class: "admin-nav-item" %>
      <%= link_to 'Rezerwacje', admins_bookings_path, class: "admin-nav-item" %>
    </div>
    <div class="nav-actions">
      <%= link_to 'User window', root_path, class: "btn btn-success mb-2"%>
      <% if user_signed_in? %>
        <%= link_to 'Log out', destroy_user_session_path, class: "btn btn-danger mt-2",  method: :delete %>
      <% end %>
    </div>
  </nav>
</div>

app/views/layouts/_contact_info.html.erb
<div class="container contacts-container">
  <div class="contacts">
    <p class="phone-info"><i class="fas fa-phone"></i> +48 123 456 789</p>
    <p class="email-info"><i class="far fa-envelope"></i> hello@sunrisehotel.com</p>
  </div>
  <div class="social-media">
    <a href="#" class="social-icon"><i class="fab fa-tripadvisor"></i></a>
    <a href="#" class="social-icon"><i class="fab fa-facebook-square"></i></a>
    <a href="#" class="social-icon"><i class="fab fa-instagram"></i></a>
    <a href="#" class="social-icon"><i class="fab fa-twitter"></i></a>
    <a href="#" class="social-icon"><i class="fab fa-youtube"></i></a>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="container footer-container">
    <div class="row row-cols-1 row-cols-lg-4">
      <div class="col mb-4 footer-box">
        <h3 class="footer-title">O Hotelu</h3>
        <p class="footer-text">Nowoczesny hotel w śródziemnomorskim stylu przy jednej z najpiękniejszych miejscowości Hiszpanii, z bezpośrednim dostępem do złocistych plaż.</p>
        <p class="footer-text">Świetny dla osób ceniących sobie spokój i ciszę, lubiących nórkować oraz zwiedzać.</p>
        <br>
        <div class="footer-btn-box">
          <%= link_to 'Rezerwacja', root_path, class: 'btn btn-success footer-btn' %>
        </div>
      </div>
      <div class="col mb-4 footer-box">
        <h3 class="footer-title">Nawigacja</h3>
        <%= link_to 'Strona główna', root_path, class: 'footer-link' %>
        <%= link_to 'Atrakcje', pages_path, class: 'footer-link' %>
        <%= link_to 'Blog', blogs_path, class: "footer-link" %>
        <%= link_to 'Kategorie', categories_path, class: "footer-link" %>
        <%= link_to 'Pokoje', rooms_path, class: "footer-link" %>
      </div>
      <div class="col mb-4 footer-box">
        <h3 class="footer-title">Co Nowego</h3>
        <%= link_to 'Tytuł artykułu numer 1', blog_path(3), class: 'footer-link' %>
        <%= link_to 'Tytuł artykułu numer 2', blog_path(2), class: 'footer-link' %>
        <%= link_to 'Tytuł atrakcji numer 1', page_path(23), class: 'footer-link' %>
        <%= link_to 'Tytuł atrakcji numer 2', page_path(24), class: 'footer-link' %>
      </div>
      <div class="col mb-4 footer-box">
        <h3 class="footer-title">Kontakt</h3>
        <p class="footer-text">SunriseHotel, Son Bou, Minorka, Hiszpania</p>
        <p class="footer-text">+48 123 456 789</p>
        <p class="footer-text">+48 123 456 789</p>
        <p class="footer-text">hello@sunrisehotel.com</p>
        <div class="footer-social-media">
          <a href="#" class="footer-icon"><i class="fab fa-tripadvisor"></i></a>
          <a href="#" class="footer-icon"><i class="fab fa-facebook-square"></i></a>
          <a href="#" class="footer-icon"><i class="fab fa-instagram"></i></a>
          <a href="#" class="footer-icon"><i class="fab fa-twitter"></i></a>
          <a href="#" class="footer-icon"><i class="fab fa-youtube"></i></a>
        </div>
      </div>
    </div>
  </div>
  <div class="copyrights-box">
    <p>&copy; 2021 | SunriseHotel</p>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show mb-0" role="alert">
    <p class="message-text"><%= notice %></p>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </button>
  </div>
<% elsif alert %>
  <div class="alert alert-danger alert-dismissible fade show mb-0" role="alert">
    <p class="message-text"><%= alert %></p>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </button>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg">
  <div class="container navbar-container">
    <div class="logo-container">
      <%= image_tag('logo-removebg-preview.png', :alt => 'Logo firmy', class: 'main-logo') %>
      <%= link_to 'SunriseHotel', root_path, class: "navbar-brand" %>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fas fa-bars"></i>
    </button>

    <div class="collapse navbar-collapse links-container" id="navbarSupportedContent">
      <div class="navbar-links ml-auto">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to 'Home', root_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to 'Atrakcje', pages_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to 'Blog', blogs_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to 'Kategorie', categories_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to 'Pokoje', rooms_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-user"></i> Konto
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <div class="admin-panel-link">
                <% if user_signed_in? %>
                  <i class="fas fa-user-circle admin-link-icon" style="display: none"></i>
                  <%= link_to 'Zaloguj', new_user_session_path, class: "nav-link", style: 'display: none' %>
                <% else %>
                  <i class="fas fa-user-circle admin-link-icon"></i>
                  <%= link_to 'Zaloguj', new_user_session_path, class: "nav-link" %>
                <% end %>
              </div>
              <div class="admin-panel-link">
                <% if user_signed_in? %>
                  <i class="fas fa-user-circle admin-link-icon"></i>
                  <%= link_to 'Admin Panel', admins_pages_path, class: "nav-link" %>
                <% end %>
              </div>
              <div class="admin-panel-link">
                <% if user_signed_in? %>
                  <i class="fas fa-cog admin-link-icon"></i>
                  <%= link_to 'Edytuj', edit_user_registration_path, class: "nav-link" %>
                <% end %>
              </div>
              <div class="dropdown-divider"></div>
              <div class="log-out-link">
                <% if user_signed_in? %>
                  <i class="fas fa-sign-out-alt admin-link-icon"></i>
                  <%= link_to 'Log out', destroy_user_session_path, class: "nav-link",  method: :delete %>
                <% end %>
              </div>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rezerwacje</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://kit.fontawesome.com/8632156806.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="admin-body">
    <%= render 'layouts/admin_nav' %>

    <div class="admin-container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%#= render 'layouts/footer' %>

  <script>
      // //--- NAVIGATION
      // const nav = document.querySelectorAll('.admin-nav')
      // const navBtn = document.querySelectorAll('.burger-btn')
      //
      // const handleNav = () => {
      //     nav.classList.toggle('admin-nav--active')
      // }
      //
      // navBtn.addEventListener('click', handleNav)
  </script>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pl">
  <head>
    <title>ShunriseHotel</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Marck+Script&family=Montserrat:wght@300;400;600;700&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/8632156806.js" crossorigin="anonymous"></script>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="body">
    <%= render 'layouts/contact_info'%>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>